### ISSUE TITLE
[초기세팅] styled-components 설치 및 GlobalStyle, theme, prettier 세팅

### ISSUE THREAD

**Issue by qwp0** [DO-SOPT-SOPKATHON-Web-1/Client#3]
## 🛠 Issue
styled-components 설치, GlobalStyle, theme, prettier 초기세팅

## 📝 To-do
- [ ] styled-components 설치
- [ ] GlobalStyle 초기 세팅
    - 기본 **reset**
       - styled-reset 을 통해 기본 css 설정 reset
    - cursor : pointer 적용
    - rem 단위를 쉽게 사용하기 위해 font-size: 10px; 선언
- [ ] theme 파일 생성 및 적용
    - 추후에 디자인 측에서 전달하는 스타일 가이드 참고하여 추가할 예정
- [ ] prettier 설치 및 세팅
